### ISSUE TITLE
Fastcgi not work

### ISSUE THREAD

**Issue by Risgit** [User65k/flash_rust_ws#29]
Unfortunately this doesn't work with PHP.
I tried to run this server under Debian and Alpine Linux.
Everything is always the same.

When trying to open the main page errors:

alp:~# /root/.cargo/bin/flash_rust_ws
2023-10-04T14:57:20.346520385+03:00 ERROR async_fcgi::client::connection - Err Connection reset by peer (os error 104)
2023-10-04T14:57:20.346586186+03:00 ERROR async_fcgi::client::connection - body #1 not done
2023-10-04T14:57:23.282810112+03:00 ERROR async_fcgi::client::connection - shutdown old con: Socket not connected (os error 107)
2023-10-04T14:57:23.283321471+03:00 ERROR async_fcgi::client::connection - Err Connection reset by peer (os error 104)
2023-10-04T14:57:23.283348968+03:00 ERROR async_fcgi::client::connection - body #1 not done
2023-10-04T14:57:24.110587953+03:00 ERROR async_fcgi::client::connection - shutdown old con: Socket not connected (os error 107)

**Comment by User65k** [comment]
Can you post the associated configuration and how you start php (if its not in the config anyway)?

**Comment by Risgit** [comment]
> Can you post the associated configuration and how you start php (if its not in the config anyway)?

Yes, of course.

pidfile  = "/var/run/frws.pid" # Optional: Write PID to this file
user = "alp"
group = "alp"

["alp.tes"]
ip = "0.0.0.0:80"
dir = "/home/alp/www/alp.tes"
index = ["index.php"]


fcgi.sock = "127.0.0.1:9000" # TCP
fcgi.exec = ["php"]
fcgi.set_script_filename = true
fcgi.set_request_uri = true

I've tried every possible option in the configuration.
The result is always the same - error 502 on the page and errors in the console.
php8.1-fpm installed.
With php7.4-fpm the errors are the same.

**Comment by User65k** [comment]
looks good (assuming there is a file "/home/alp/www/alp.tes/index.php")

How do you start php? It's not started by the server (You would need to add `fcgi.bin.path` if you want that).

Do you see php listening on port 9000 (using `ss -ltn`) ?

**Comment by Risgit** [comment]
Step by step, using Debian as an example.

1. Installing flash_rust_ws.
cargo install --git https://github.com/User65k/flash_rust_ws.git

2. Creating a configuration file /etc/default/frws.toml
I write the config in it.

####################################

pidfile = "/var/run/frws.pid" # Optional: Write PID to this file
user = "www-data"
group = "www-data"

["debi.tes"]
ip = "0.0.0.0:80"
dir = "/home/deb/www/debi.tes"
index = ["index.html"]

###################################

I see that the server works fine with html and normally serves the page with the file index.html

3. Installing php7.4-fpm

I'm running PHP.

systemctl restart php7.4-fpm

I look in the php configuration file and it works via tsp or socket.

4. Edit a configuration file frws

############################

pidfile = "/var/run/frws.pid" # Optional: Write PID to this file
user = "www-data"
group = "www-data"

["debi.tes"]
ip = "0.0.0.0:80"
dir = "/home/deb/www/debi.tes"
index = ["index.php"]

fcgi.sock = "/run/php/php7.4-fpm.sock"
fcgi.exec = ["php"]
fcgi.set_script_filename = true
fcgi.set_request_uri = true

##############################

5. I restart the server, try to open the page with the site and see a 502 error.
The following errors appear in the console.

root@debian:~# /root/frws/flash_rust_ws start
2023-10-04 16:23:55 UTC ERROR flash_rust_ws::dispatch - Broken pipe (os error 32)
2023-10-04 16:24:17 UTC ERROR flash_rust_ws::dispatch - FCGI app did not respond
2023-10-04 16:24:17 UTC ERROR flash_rust_ws::dispatch - FCGI app did not respond

6. When I try to add a link to the PHP executable file to the config frws

fcgi.bin.path = "/usr/sbin/php-fpm7.4"

it gives an error:

root@debian:~# /root/frws/flash_rust_ws start
2023-10-04 16:27:31 UTC ERROR flash_rust_ws - Configuration error!
"debi.tes/": Address already in use (os error 98)


I can install flash_rust_ws on my test VPS and give you access.

**Comment by User65k** [comment]
Ok, I get the same on fedora. I only tried with `php-cgi` so far.

`php-fpm` does not seem to adhere to the fcgi way of spawning the server, so `fcgi.bin.path` won't work.

I got from an error to a black page (that should not be blank) by fiddling with `fcgi.params`. I guess it needs some value set. I will try to figure out what

**Comment by Risgit** [comment]
> `php-fpm` does not seem to adhere to the fcgi way of spawning the server

Installed php82-cgi
Added to config 
fcgi.bin.path = "/usr/bin/php-cgi82"

Restarted frws
I open the site.
I have an error 
alp:~# /usr/sbin/flash_rust_ws
2023-10-05 09:33:34 UTC ERROR flash_rust_ws::dispatch::fcgi - FCGI app exit: exit status: 0
2023-10-05 09:38:17 UTC ERROR async_fcgi::client::connection - Err Connection reset by peer (os error 104)
2023-10-05 09:38:17 UTC ERROR async_fcgi::client::connection - allive: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2023-10-05 09:38:17 UTC ERROR flash_rust_ws::dispatch - Connection reset by peer (os error 104)
2023-10-05 09:38:19 UTC ERROR async_fcgi::client::connection - shutdown old con: Socket not connected (os error 107)
2023-10-05 09:38:19 UTC ERROR flash_rust_ws::dispatch - Connection refused (os error 111)

**Comment by User65k** [comment]
Ok, I got that too (Trying from chromium).
Then I tried curl and firefox.
And it works with:
```toml
[bla]
ip = "0.0.0.0:8080"
dir = "/tmp/"
index = ["index.php"]

fcgi.sock = "/run/php_test.sock"
#fcgi.sock = "127.0.0.1:9000"
fcgi.exec = ["php"]
fcgi.set_script_filename = true
fcgi.set_request_uri = true
fcgi.bin.path = "/usr/bin/php-cgi"
fcgi.bin.environment = {PHP_FCGI_CHILDREN = "1", PHP_FCGI_MAX_REQUESTS = "10000"}
```

php-fpm is now reporting 404 with the same config (without `fcgi.bin`).
```toml
[bla]
ip = "0.0.0.0:8080"
dir = "/tmp/"
index = ["index.php"]

fcgi.sock = "127.0.0.1:9000"
fcgi.exec = ["php"]
fcgi.set_script_filename = true
fcgi.set_request_uri = true
```
(I suppose I have to set some doc root in FPM)

I have no Idea why the browser would matter, but I will try to debug it

**Comment by Risgit** [comment]
**User65k**, thank You!
I tried firefox - page load my index.php with phpinfo();
But text only. Without inline styles.

`PHP Version 7.4.33
System 	Linux debian 5.10.0-23-amd64 #1 SMP Debian 5.10.179-3 (2023-07-27) x86_64
Build Date 	Jun 9 2023 16:51:37
Server API 	FPM/FastCGI
Virtual Directory Support 	disabled
Configuration File (php.ini) Path 	/etc/php/7.4/fpm
Loaded Configuration File 	/etc/php/7.4/fpm/php.ini
Scan this dir for additional .ini files 	/etc/php/7.4/fpm/conf.d `

In console errors:

`Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).
Source: color: #007700 debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).
Source: color: #DD0000 debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).
Source: color: #DD0000 debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). debi.tes
Content-Security-Policy: The page’s settings blocked the loading of a resource at data:image/png;base64,iVBORw0KGgoAAAANSU… (“default-src”). 2 debi.tes`

**Comment by User65k** [comment]
Yes, that's the overly protective default CSP.

You need to allow images from data and inline css, like this:
```toml
["debi.tes"]
header={Content-Security-Policy="default-src 'self';frame-ancestors 'self';img-src data:; style-src 'unsafe-inline'"}
```
or just turn it off:
```toml
["debi.tes"]
header={Content-Security-Policy=""}
```

**Comment by Risgit** [comment]
Thanks a lot!
It worked in Firefox! It doesn't work in Chrome-like browsers.

At first, however, there were errors about the absence of the DOCUMENT_ROOT, but I added a line with the fcgi parameters and the errors disappeared.

fcgi.params = {DOCUMENT_ROOT="/home/alp/www/alp.tes"}

There is a suspicion that fcgi needs to set parameters, as in nginx

fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;
fastcgi_param  HTTP_HOST		  $host;

But the frws server does not accept configuration variables.

**Comment by User65k** [comment]
Yes, I only set the [must headers](https://docs.rs/async-fcgi/latest/async_fcgi/client/connection/struct.Connection.html#method.forward) from the [Spec](https://datatracker.ietf.org/doc/html/rfc3875#section-4.1)
and optionally script_filename and request_uri. And all the HTTP_* ones.

The issue with chrome seems to be related to the Accept header:
```py
from socket import socket
s = socket()
s.connect(('127.0.0.1',8080))
s.sendall(b"\r\n".join([b"GET / HTTP/1.1",
b"Host: 127.0.0.1:8080",
b"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
b"\r\n"]))
assert len(s.recv(4096))!=276
```
However, the same value works, when using requests
```py
import requests
r=requests.get("http://127.0.0.1:8080/",headers={
'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
})
assert len(r.text)!=276
```

I don't realy see a difference on the wire https://app.packetsafari.com/analyze/l/xVkZBYsBW6-oT3TQtszn

**Comment by Risgit** [comment]
Installed v0.4.4.
Works in chrome!
Great job!

Is it possible to somehow set up something like a mod_rewrite in Apache?
The debi.tes page opens, but the debi.tes/articles page shows a 404 error.
